// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: partition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for blocking communication between specified peer groups
type BlockPeersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IDs of the peers to block
	PeerIds       []int32 `protobuf:"varint,1,rep,packed,name=peerIds,proto3" json:"peerIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPeersRequest) Reset() {
	*x = BlockPeersRequest{}
	mi := &file_partition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPeersRequest) ProtoMessage() {}

func (x *BlockPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPeersRequest.ProtoReflect.Descriptor instead.
func (*BlockPeersRequest) Descriptor() ([]byte, []int) {
	return file_partition_proto_rawDescGZIP(), []int{0}
}

func (x *BlockPeersRequest) GetPeerIds() []int32 {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

var File_partition_proto protoreflect.FileDescriptor

const file_partition_proto_rawDesc = "" +
	"\n" +
	"\x0fpartition.proto\x12\x04raft\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x11BlockPeersRequest\x12\x18\n" +
	"\apeerIds\x18\x01 \x03(\x05R\apeerIds2\x8f\x01\n" +
	"\tPartition\x12=\n" +
	"\n" +
	"blockPeers\x12\x17.raft.BlockPeersRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x11clearBlockedPeers\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB:Z8github.com/niklhut/raft_go/internal/transport/grpc/protob\x06proto3"

var (
	file_partition_proto_rawDescOnce sync.Once
	file_partition_proto_rawDescData []byte
)

func file_partition_proto_rawDescGZIP() []byte {
	file_partition_proto_rawDescOnce.Do(func() {
		file_partition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partition_proto_rawDesc), len(file_partition_proto_rawDesc)))
	})
	return file_partition_proto_rawDescData
}

var file_partition_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_partition_proto_goTypes = []any{
	(*BlockPeersRequest)(nil), // 0: raft.BlockPeersRequest
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_partition_proto_depIdxs = []int32{
	0, // 0: raft.Partition.blockPeers:input_type -> raft.BlockPeersRequest
	1, // 1: raft.Partition.clearBlockedPeers:input_type -> google.protobuf.Empty
	1, // 2: raft.Partition.blockPeers:output_type -> google.protobuf.Empty
	1, // 3: raft.Partition.clearBlockedPeers:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_partition_proto_init() }
func file_partition_proto_init() {
	if File_partition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partition_proto_rawDesc), len(file_partition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_partition_proto_goTypes,
		DependencyIndexes: file_partition_proto_depIdxs,
		MessageInfos:      file_partition_proto_msgTypes,
	}.Build()
	File_partition_proto = out.File
	file_partition_proto_goTypes = nil
	file_partition_proto_depIdxs = nil
}
