// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: partition.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Partition_BlockPeers_FullMethodName        = "/raft.Partition/blockPeers"
	Partition_ClearBlockedPeers_FullMethodName = "/raft.Partition/clearBlockedPeers"
)

// PartitionClient is the client API for Partition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for partitioning the cluster
type PartitionClient interface {
	// Blocks communication between specified peer groups
	BlockPeers(ctx context.Context, in *BlockPeersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Heals the partition
	ClearBlockedPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type partitionClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionClient(cc grpc.ClientConnInterface) PartitionClient {
	return &partitionClient{cc}
}

func (c *partitionClient) BlockPeers(ctx context.Context, in *BlockPeersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Partition_BlockPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionClient) ClearBlockedPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Partition_ClearBlockedPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionServer is the server API for Partition service.
// All implementations must embed UnimplementedPartitionServer
// for forward compatibility.
//
// Service for partitioning the cluster
type PartitionServer interface {
	// Blocks communication between specified peer groups
	BlockPeers(context.Context, *BlockPeersRequest) (*emptypb.Empty, error)
	// Heals the partition
	ClearBlockedPeers(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedPartitionServer()
}

// UnimplementedPartitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartitionServer struct{}

func (UnimplementedPartitionServer) BlockPeers(context.Context, *BlockPeersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockPeers not implemented")
}
func (UnimplementedPartitionServer) ClearBlockedPeers(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBlockedPeers not implemented")
}
func (UnimplementedPartitionServer) mustEmbedUnimplementedPartitionServer() {}
func (UnimplementedPartitionServer) testEmbeddedByValue()                   {}

// UnsafePartitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionServer will
// result in compilation errors.
type UnsafePartitionServer interface {
	mustEmbedUnimplementedPartitionServer()
}

func RegisterPartitionServer(s grpc.ServiceRegistrar, srv PartitionServer) {
	// If the following call pancis, it indicates UnimplementedPartitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Partition_ServiceDesc, srv)
}

func _Partition_BlockPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).BlockPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Partition_BlockPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).BlockPeers(ctx, req.(*BlockPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Partition_ClearBlockedPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).ClearBlockedPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Partition_ClearBlockedPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).ClearBlockedPeers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Partition_ServiceDesc is the grpc.ServiceDesc for Partition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Partition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.Partition",
	HandlerType: (*PartitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "blockPeers",
			Handler:    _Partition_BlockPeers_Handler,
		},
		{
			MethodName: "clearBlockedPeers",
			Handler:    _Partition_ClearBlockedPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partition.proto",
}
