services:
  raft_node_2:
    image: registry.niklabs.de/niklhut/raftgo
    container_name: raft_node_2
    ports:
      - "10002:10002"
    networks:
      - raftnet
    command:
      - peer
      - --id
      - '2'
      - --port
      - '10002'
      - --address
      - 10.10.2.182
      - --peers
      - 1:10.10.2.181:10001,3:10.10.2.183:10003
      - --compaction-threshold
      - '1000'
      - --use-distributed-actor-system

networks:
  raftnet:
    driver: bridge
